--DROP TYPE cover_type;
--DROP TYPE status_user;
--DROP TYPE order_status;
--DROP TYPE payment_method;
DROP TYPE IF EXISTS cover_type, status_user, order_status, payment_method;
--DROP TABLE IF EXISTS ordered_book;
--DROP TABLE IF EXISTS purchase;
--DROP TABLE IF EXISTS book_author;
--DROP TABLE IF EXISTS book;
--DROP TABLE IF EXISTS publisher;
--DROP TABLE IF EXISTS genre;
--DROP TABLE IF EXISTS cover_type;
--DROP TABLE IF EXISTS account;
DROP DATABASE IF EXISTS web_bookstore;
